import { Injectable } from '@nestjs/common';
import type { Company, Employee, PayRun, PayRunLine } from '@prisma/client';
import PDFDocument from 'pdfkit';
import { amountInWords } from '../invoices/invoice-pdf.service';
import { pickDocTemplate, resolveTemplate } from '../invoices/invoice-template';
import {
  pdfLang,
  registerPdfFonts,
  type PdfLang,
} from '../common/pdf-locale';
import { periodLabel } from './payroll.math';

const LABELS: Record<PdfLang, Record<string, string>> = {
  en: {
    payslipFor: 'Payslip for',
    employeeName: 'Employee Name', employeeCode: 'Employee Code',
    designation: 'Designation', branch: 'Branch', joinDate: 'Date of Joining',
    pan: 'PAN', uan: 'UAN', esiNo: 'ESI No', bankAc: 'Bank A/c', ifsc: 'IFSC',
    workingDays: 'Working days', lopDays: 'LOP days', paidDays: 'Paid days',
    basic: 'Basic', hra: 'HRA', conveyance: 'Conveyance', other: 'Other Allowances',
    pfEmployee: 'PF (Employee)', esiEmployee: 'ESI (Employee)', pt: 'Professional Tax', tds: 'TDS',
    earnings: 'EARNINGS', deductions: 'DEDUCTIONS', amount: 'AMOUNT (Rs.)',
    grossEarnings: 'Gross Earnings', totalDeductions: 'Total Deductions',
    netPay: 'NET PAY', netPayWords: 'Net Pay in words',
    footer1: 'This is a computer-generated payslip and does not require a signature.',
    footer2: 'Generated by RGS',
  },
  ta: {
    payslipFor: 'சம்பளப் பட்டியல் —',
    employeeName: 'பணியாளர் பெயர்', employeeCode: 'பணியாளர் குறியீடு',
    designation: 'பதவி', branch: 'கிளை', joinDate: 'சேர்ந்த தேதி',
    pan: 'PAN', uan: 'UAN', esiNo: 'ESI எண்', bankAc: 'வங்கிக் கணக்கு', ifsc: 'IFSC',
    workingDays: 'வேலை நாட்கள்', lopDays: 'LOP நாட்கள்', paidDays: 'ஊதிய நாட்கள்',
    basic: 'அடிப்படை', hra: 'வீட்டு வாடகைப் படி (HRA)', conveyance: 'பயணப்படி', other: 'பிற படிகள்',
    pfEmployee: 'PF (பணியாளர்)', esiEmployee: 'ESI (பணியாளர்)', pt: 'தொழில் வரி', tds: 'TDS',
    earnings: 'வரவுகள்', deductions: 'பிடித்தங்கள்', amount: 'தொகை (ரூ.)',
    grossEarnings: 'மொத்த வரவு', totalDeductions: 'மொத்தப் பிடித்தம்',
    netPay: 'நிகர சம்பளம்', netPayWords: 'நிகர சம்பளம் எழுத்தில்',
    footer1: 'இது கணினியில் உருவாக்கப்பட்ட சம்பளப் பட்டியல்; கையொப்பம் தேவையில்லை.',
    footer2: 'RGS மூலம் உருவாக்கப்பட்டது',
  },
  hi: {
    payslipFor: 'पेस्लिप —',
    employeeName: 'कर्मचारी का नाम', employeeCode: 'कर्मचारी कोड',
    designation: 'पदनाम', branch: 'शाखा', joinDate: 'ज्वाइनिंग तिथि',
    pan: 'PAN', uan: 'UAN', esiNo: 'ESI नं', bankAc: 'बैंक खाता', ifsc: 'IFSC',
    workingDays: 'कार्य दिवस', lopDays: 'LOP दिन', paidDays: 'भुगतान दिवस',
    basic: 'मूल वेतन', hra: 'HRA', conveyance: 'यात्रा भत्ता', other: 'अन्य भत्ते',
    pfEmployee: 'PF (कर्मचारी)', esiEmployee: 'ESI (कर्मचारी)', pt: 'व्यावसायिक कर', tds: 'TDS',
    earnings: 'आय', deductions: 'कटौतियाँ', amount: 'राशि (रु.)',
    grossEarnings: 'सकल आय', totalDeductions: 'कुल कटौती',
    netPay: 'शुद्ध वेतन', netPayWords: 'शुद्ध वेतन शब्दों में',
    footer1: 'यह कंप्यूटर से तैयार पेस्लिप है और इस पर हस्ताक्षर की आवश्यकता नहीं है।',
    footer2: 'RGS द्वारा तैयार',
  },
};

type PayslipData = PayRunLine & {
  employee: Employee & { branch: { name: string } | null };
  payRun: PayRun & { company: Company };
};

const inr = (n: number | string) =>
  Number(n).toLocaleString('en-IN', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });

/** Mask everything but the last 4 characters of an account number. */
const maskAccount = (acc: string): string =>
  acc.length <= 4 ? acc : `${'*'.repeat(acc.length - 4)}${acc.slice(-4)}`;

@Injectable()
export class PayslipPdfService {
  async render(data: PayslipData, lang?: string): Promise<Buffer> {
    const L = LABELS[pdfLang(lang)];
    const { employee, payRun } = data;
    const company = payRun.company;
    const period = periodLabel(payRun.year, payRun.month);
    // Per-form print layout (accent / footer); other invoice-only fields N/A.
    const tpl = resolveTemplate(pickDocTemplate(company, 'payslip'));
    const accent = tpl.accentColor;
    const displayName = company.printName?.trim() || company.name;

    const doc = new PDFDocument({ size: 'A4', margin: 40 });
    const F = registerPdfFonts(doc, pdfLang(lang));
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    const finished = new Promise<Buffer>((resolve) =>
      doc.on('end', () => resolve(Buffer.concat(chunks))),
    );

    const M = 40; // margin
    const W = doc.page.width - M * 2;

    // ---- Header ----
    if (company.logo) {
      try {
        const logoBuf = Buffer.from(company.logo.slice(company.logo.indexOf(',') + 1), 'base64');
        doc.image(logoBuf, M + W - 110, M, { fit: [110, 44] });
      } catch {
        /* malformed logo: skip */
      }
    }
    doc.fontSize(18).font(F.bold).fillColor(accent).text(displayName, M, M);
    doc.fontSize(9).font(F.regular).fillColor('#555');
    const addr = [
      company.addressLine1,
      company.addressLine2,
      [company.city, company.pincode].filter(Boolean).join(' - '),
    ]
      .filter(Boolean)
      .join(', ');
    if (addr) doc.text(addr);
    if (company.gstin) doc.text(`GSTIN: ${company.gstin}`);

    doc.moveDown(0.5);
    doc
      .fontSize(14)
      .font(F.bold)
      .fillColor(accent)
      .text(`${L.payslipFor} ${period}`, M);
    const psRuleY = doc.y + 2;
    doc.moveTo(M, psRuleY).lineTo(M + W, psRuleY).lineWidth(1.5).strokeColor(accent).stroke();
    doc.strokeColor('#000').fillColor('#000');
    doc.y = psRuleY + 4;

    // ---- Employee block (two columns) ----
    const labelW = 90;
    const colHalf = W / 2;
    const blockTop = doc.y + 8;

    doc.rect(M, blockTop - 4, W, 84).fill('#f8fafc');
    doc.fillColor('#000');

    const field = (label: string, value: string, x: number, y: number) => {
      doc.fontSize(8.5).font(F.bold).fillColor('#475569')
        .text(label, x, y, { width: labelW });
      doc.font(F.regular).fillColor('#000')
        .text(value, x + labelW, y, { width: colHalf - labelW - 12 });
    };

    const left: [string, string][] = [
      [L.employeeName, employee.name],
      [L.employeeCode, employee.code],
      [L.designation, employee.designation ?? '—'],
      [L.branch, employee.branch?.name ?? '—'],
      [L.joinDate, employee.joinDate.toLocaleDateString('en-IN')],
    ];
    const right: [string, string][] = [
      [L.pan, employee.pan ?? '—'],
      [L.uan, employee.uan ?? '—'],
      [L.esiNo, employee.esiNo ?? '—'],
      [
        L.bankAc,
        employee.bankAccountNo
          ? `${maskAccount(employee.bankAccountNo)}${employee.bankName ? ` (${employee.bankName})` : ''}`
          : '—',
      ],
      [L.ifsc, employee.bankIfsc ?? '—'],
    ];
    left.forEach(([label, value], i) => field(label, value, M + 6, blockTop + 2 + i * 15));
    right.forEach(([label, value], i) => field(label, value, M + colHalf + 6, blockTop + 2 + i * 15));

    // ---- Attendance line ----
    let y = blockTop + 88;
    const workingDays = Number(data.workingDays);
    const lopDays = Number(data.lopDays);
    const paidDays = workingDays - lopDays;
    doc
      .fontSize(9)
      .font(F.regular)
      .fillColor('#000')
      .text(
        `${L.workingDays}: ${workingDays}    |    ${L.lopDays}: ${lopDays}    |    ${L.paidDays}: ${paidDays}`,
        M,
        y,
        { width: W },
      );
    y += 22;

    // ---- Earnings / Deductions table ----
    const earnings: [string, number][] = [
      [L.basic, Number(data.basic)],
      [L.hra, Number(data.hra)],
      [L.conveyance, Number(data.conveyance)],
      [L.other, Number(data.otherAllowances)],
    ].filter(([label, amount]) => label === L.basic || amount !== 0) as [string, number][];

    const deductions: [string, number][] = (
      [
        [L.pfEmployee, Number(data.pfEmployee)],
        [L.esiEmployee, Number(data.esiEmployee)],
        [L.pt, Number(data.pt)],
        [L.tds, Number(data.tds)],
      ] as [string, number][]
    ).filter(([, amount]) => amount !== 0);

    const colW = W / 2;
    const amtW = 80;

    // Table header — accent band with white uppercase labels (matches invoices).
    doc.rect(M, y - 4, W, 18).fill(accent);
    doc.fillColor('#ffffff').fontSize(7.5).font(F.bold);
    doc.text(L.earnings.toUpperCase(), M + 6, y + 1.5, { width: colW - amtW - 12, characterSpacing: 0.4 });
    doc.text(L.amount.toUpperCase(), M + colW - amtW - 6, y + 1.5, { width: amtW, align: 'right', characterSpacing: 0.4 });
    doc.text(L.deductions.toUpperCase(), M + colW + 6, y + 1.5, { width: colW - amtW - 12, characterSpacing: 0.4 });
    doc.text(L.amount.toUpperCase(), M + W - amtW - 6, y + 1.5, { width: amtW, align: 'right', characterSpacing: 0.4 });
    doc.fillColor('#1e293b').font(F.regular);
    y += 18;
    const rowsTop = y;

    const rows = Math.max(earnings.length, deductions.length);
    for (let i = 0; i < rows; i++) {
      doc.fontSize(9);
      const e = earnings[i];
      if (e) {
        doc.text(e[0], M + 6, y, { width: colW - amtW - 12 });
        doc.text(inr(e[1]), M + colW - amtW - 6, y, { width: amtW, align: 'right' });
      }
      const d = deductions[i];
      if (d) {
        doc.text(d[0], M + colW + 6, y, { width: colW - amtW - 12 });
        doc.text(inr(d[1]), M + W - amtW - 6, y, { width: amtW, align: 'right' });
      }
      y += 15;
      doc
        .moveTo(M, y - 3)
        .lineTo(M + W, y - 3)
        .strokeColor('#e2e8f0')
        .lineWidth(0.5)
        .stroke();
    }

    // Totals row
    doc.rect(M, y - 3, W, 16).fill('#f8fafc');
    doc.fillColor('#000').fontSize(9).font(F.bold);
    doc.text(L.grossEarnings, M + 6, y, { width: colW - amtW - 12 });
    doc.text(inr(Number(data.gross)), M + colW - amtW - 6, y, { width: amtW, align: 'right' });
    doc.text(L.totalDeductions, M + colW + 6, y, { width: colW - amtW - 12 });
    doc.text(inr(Number(data.totalDeductions)), M + W - amtW - 6, y, {
      width: amtW,
      align: 'right',
    });
    y += 16;

    // Column divider
    doc
      .moveTo(M + colW, rowsTop)
      .lineTo(M + colW, y - 3)
      .strokeColor('#e2e8f0')
      .lineWidth(0.5)
      .stroke();

    // ---- Net pay (branded accent band, white text) ----
    y += 10;
    const netPay = Number(data.netPay);
    doc.rect(M, y - 5, W, 26).fill(accent);
    doc
      .fillColor('#ffffff')
      .font(F.bold)
      .fontSize(12.5)
      .text(L.netPay, M + 8, y, { width: 200 });
    doc.text(`Rs. ${inr(netPay)}`, M + W - 208, y, { width: 200, align: 'right' });
    doc.fillColor('#000');
    y += 28;

    doc
      .font(F.oblique)
      .fontSize(8)
      .fillColor('#555')
      .text(`${L.netPayWords}: ${amountInWords(netPay)}`, M, y, { width: W });

    // ---- Footer ----
    // Drop the bottom margin so the absolutely-positioned footer near the page
    // edge doesn't trip PDFKit's auto-pagination onto a blank second page.
    doc.page.margins.bottom = 0;
    doc
      .moveTo(M, doc.page.height - 66)
      .lineTo(M + W, doc.page.height - 66)
      .lineWidth(0.5)
      .strokeColor('#e2e8f0')
      .stroke();
    doc
      .font(F.regular)
      .fontSize(8)
      .fillColor('#94a3b8')
      .text(
        L.footer1,
        M,
        doc.page.height - 60,
        { width: W, align: 'center' },
      )
      .text(tpl.footerText?.trim() || L.footer2, M, doc.page.height - 48, { width: W, align: 'center' });

    doc.end();
    return finished;
  }
}
