import { Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import { registerPdfFonts, pdfLang, type PdfLang } from '../common/pdf-locale';

export interface QuotePdfData {
  quoteNo: string;
  invoiceNo: string | null;
  status: string;
  description: string;
  amount: number;
  gstApplicable: boolean;
  gstPercent: number;
  gstAmount: number;
  total: number;
  billingType: string;
  dueDate: Date | null;
  notes: string | null;
  createdAt: Date;
  auditor: {
    displayName: string;
    firmName: string | null;
    email: string | null;
    phone: string | null;
    city: string | null;
    state: string | null;
  };
  client: { name: string; email: string };
}

const L: Record<PdfLang, Record<string, string>> = {
  en: {
    quotation: 'QUOTATION', invoice: 'TAX INVOICE', billedTo: 'Billed to',
    description: 'Description', amount: 'Amount', subtotal: 'Subtotal', gst: 'GST',
    total: 'Total', dueDate: 'Due date', notes: 'Notes', date: 'Date',
    accepted: 'ACCEPTED', declined: 'DECLINED', pending: 'PENDING',
    billing: 'Billing', footer: 'Generated by RGS',
    monthly: 'Monthly', annual: 'Annual', retainer: 'Retainer', bundle: 'Bundle', custom: 'Custom',
  },
  ta: {
    quotation: 'மேற்கோள்', invoice: 'வரி விலைப்பட்டியல்', billedTo: 'பெறுநர்',
    description: 'விளக்கம்', amount: 'தொகை', subtotal: 'கூட்டுத்தொகை', gst: 'GST',
    total: 'மொத்தம்', dueDate: 'செலுத்த வேண்டிய தேதி', notes: 'குறிப்புகள்', date: 'தேதி',
    accepted: 'ஏற்கப்பட்டது', declined: 'நிராகரிக்கப்பட்டது', pending: 'நிலுவையில்',
    billing: 'பில்லிங்', footer: 'RGS மூலம் உருவாக்கப்பட்டது',
    monthly: 'மாதாந்திரம்', annual: 'வருடாந்திரம்', retainer: 'ரிடெய்னர்', bundle: 'தொகுப்பு', custom: 'தனிப்பயன்',
  },
  hi: {
    quotation: 'कोटेशन', invoice: 'टैक्स इनवॉइस', billedTo: 'बिल प्राप्तकर्ता',
    description: 'विवरण', amount: 'राशि', subtotal: 'उप-योग', gst: 'GST',
    total: 'कुल', dueDate: 'देय तिथि', notes: 'नोट्स', date: 'तिथि',
    accepted: 'स्वीकृत', declined: 'अस्वीकृत', pending: 'लंबित',
    billing: 'बिलिंग', footer: 'RGS द्वारा निर्मित',
    monthly: 'मासिक', annual: 'वार्षिक', retainer: 'रिटेनर', bundle: 'बंडल', custom: 'कस्टम',
  },
};

@Injectable()
export class AuditorPdfService {
  async render(data: QuotePdfData, lang?: string): Promise<Buffer> {
    const t = L[pdfLang(lang)];
    const accepted = data.status === 'ACCEPTED';
    const doc = new PDFDocument({ size: 'A4', margin: 48 });
    const F = registerPdfFonts(doc, pdfLang(lang));
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    const finished = new Promise<Buffer>((resolve) =>
      doc.on('end', () => resolve(Buffer.concat(chunks))),
    );

    const M = 48;
    const W = doc.page.width - M * 2;
    const accent = '#673de6';
    const inr = (n: number) =>
      `₹${n.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

    // Header — auditor identity (left) + doc title (right)
    doc.fillColor(accent).font(F.bold).fontSize(18).text(data.auditor.displayName, M, M, { width: W * 0.6 });
    doc.fillColor('#555').font(F.regular).fontSize(9);
    if (data.auditor.firmName) doc.text(data.auditor.firmName, { width: W * 0.6 });
    const loc = [data.auditor.city, data.auditor.state].filter(Boolean).join(', ');
    if (loc) doc.text(loc, { width: W * 0.6 });
    const contact = [data.auditor.phone, data.auditor.email].filter(Boolean).join('  ·  ');
    if (contact) doc.text(contact, { width: W * 0.6 });

    doc.fillColor(accent).font(F.bold).fontSize(20).text(accepted ? t.invoice : t.quotation, M, M, { width: W, align: 'right' });
    doc.fillColor('#000').font(F.regular).fontSize(10).text(
      `${accepted && data.invoiceNo ? data.invoiceNo : data.quoteNo}`,
      M,
      M + 26,
      { width: W, align: 'right' },
    );
    doc.fillColor('#888').fontSize(9).text(
      `${t.date}: ${new Date(data.createdAt).toLocaleDateString('en-IN')}`,
      M,
      M + 42,
      { width: W, align: 'right' },
    );

    // Accent rule under the header band.
    doc.moveTo(M, M + 66).lineTo(M + W, M + 66).lineWidth(1.5).strokeColor(accent).stroke();
    doc.strokeColor('#000');

    // Billed-to
    doc.moveDown(3);
    let y = Math.max(doc.y, M + 90);
    doc.fillColor('#888').font(F.bold).fontSize(8).text(t.billedTo.toUpperCase(), M, y);
    doc.fillColor('#000').font(F.bold).fontSize(11).text(data.client.name, M, doc.y);
    doc.font(F.regular).fontSize(9).fillColor('#555').text(data.client.email);

    // Line table
    y = doc.y + 20;
    doc.rect(M, y, W, 24).fill(accent);
    doc.fillColor('#fff').font(F.bold).fontSize(9);
    doc.text(t.description, M + 10, y + 7, { width: W - 140 });
    doc.text(t.amount, M + W - 130, y + 7, { width: 120, align: 'right' });
    y += 24;
    doc.fillColor('#000').font(F.regular).fontSize(10);
    const descH = doc.heightOfString(data.description, { width: W - 150 });
    doc.text(data.description, M + 10, y + 8, { width: W - 150 });
    doc.text(inr(data.amount), M + W - 130, y + 8, { width: 120, align: 'right' });
    y += Math.max(descH, 16) + 16;
    doc.moveTo(M, y).lineTo(M + W, y).strokeColor('#e2e8f0').stroke();

    // Totals
    const totX = M + W - 230;
    const valX = M + W - 130;
    y += 12;
    const row = (label: string, val: string, bold = false) => {
      doc.font(bold ? F.bold : F.regular).fontSize(bold ? 12 : 10).fillColor(bold ? accent : '#334155');
      doc.text(label, totX, y, { width: 100 });
      doc.text(val, valX, y, { width: 120, align: 'right' });
      y += bold ? 22 : 18;
    };
    if (data.gstApplicable) {
      row(t.subtotal, inr(data.amount));
      row(`${t.gst} ${data.gstPercent}%`, inr(data.gstAmount));
    }
    // Crisp accent rule above the grand total.
    doc.moveTo(totX, y).lineTo(M + W, y).lineWidth(0.8).strokeColor(accent).stroke();
    doc.strokeColor('#000');
    y += 4;
    row(t.total, inr(data.total), true);

    // Meta (status / due date / notes)
    y += 10;
    doc.font(F.regular).fontSize(9).fillColor('#555');
    const statusLabel = accepted ? t.accepted : data.status === 'DECLINED' ? t.declined : t.pending;
    doc.text(`${statusLabel}`, M, y);
    if (data.billingType && data.billingType !== 'one_time') {
      doc.text(`${t.billing}: ${t[data.billingType] ?? data.billingType}`, M, doc.y);
    }
    if (data.dueDate) doc.text(`${t.dueDate}: ${new Date(data.dueDate).toLocaleDateString('en-IN')}`, M, doc.y);
    if (data.notes) {
      doc.moveDown(0.5);
      doc.font(F.bold).fontSize(9).fillColor('#334155').text(t.notes);
      doc.font(F.regular).fontSize(9).fillColor('#555').text(data.notes, { width: W });
    }

    // Footer
    doc.page.margins.bottom = 0;
    doc.moveTo(M, doc.page.height - 66).lineTo(M + W, doc.page.height - 66).lineWidth(0.5).strokeColor('#e2e8f0').stroke();
    doc.strokeColor('#000').font(F.regular).fontSize(8).fillColor('#94a3b8')
      .text(t.footer, M, doc.page.height - 58, { width: W, align: 'center' });

    doc.end();
    return finished;
  }
}
